services:
  - type: web
    name: login-signup-system
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: RECAPTCHA_SECRET_KEY
        sync: false
      - key: RECAPTCHA_SITE_KEY
        sync: false
    healthCheckPath: /
